"""Cross-check production planner against the independent brute-force oracle.

Expected UTC instants are generated by ``tests.reference`` which enumerates
every UTC minute of the year — a different algorithm sharing only the system
tz database. We run a DST zone (America/New_York) and a non-DST zone
(Asia/Shanghai), and the tricky wall time 02:30 which both gaps and repeats.
"""
from __future__ import annotations

from datetime import date

import pytest

from scheduler.planner.occurrence import plan_window
from scheduler.planner.spec import parse_spec
from .reference import reference_gap_dates, reference_occurrences


def _spec(zone, at, **over):
    body = {
        "name": "ref", "timezone": zone, "frequency": "daily", "at": at,
        "start_date": "2024-01-01", "end_date": "2024-12-31",
        "executor": {"type": "log"},
    }
    body.update(over)
    return parse_spec(body)


@pytest.mark.parametrize("zone", ["America/New_York", "Asia/Shanghai"])
@pytest.mark.parametrize("at", ["02:30", "09:15"])
def test_full_year_matches_minute_grid_oracle(zone, at):
    spec = _spec(zone, at)
    # oracle: independent computation
    ref = reference_occurrences(spec, 2024)
    # production
    win = plan_window(spec, date(2024, 1, 1), date(2024, 12, 31))
    prod = [(f.due_utc, f.date_local, f.fold, f.kind.value) for f in win.fires]
    oracle = [(f.due_utc, f.date_local, f.fold, f.kind) for f in ref]

    print(f"\n[oracle {zone} {at}] oracle={len(oracle)} produced={len(prod)}")
    if zone == "America/New_York" and at == "02:30":
        # 366 local days; the single spring-forward gap has no instant, and
        # 02:30 is post-transition (not ambiguous) on the fall-back day.
        assert len(prod) == 365
    if zone == "Asia/Shanghai":
        assert len(prod) == 366  # no DST, leap year

    assert prod == oracle, (
        f"mismatch for {zone} {at}: "
        f"only-oracle={sorted(set(oracle) - set(prod))[:5]} "
        f"only-prod={sorted(set(prod) - set(oracle))[:5]}"
    )


@pytest.mark.parametrize("zone", ["America/New_York", "Asia/Shanghai"])
def test_gap_dates_match_oracle(zone):
    spec = _spec(zone, "02:30")
    gaps_oracle = reference_gap_dates(spec, 2024)
    win = plan_window(spec, date(2024, 1, 1), date(2024, 12, 31))
    gaps_prod = sorted(s.date_local for s in win.skipped if s.reason.value == "gap")
    print(f"\n[gaps {zone}] oracle={gaps_oracle} prod={gaps_prod}")
    assert gaps_prod == gaps_oracle
    if zone == "America/New_York":
        assert gaps_oracle == [date(2024, 3, 10)]


def test_weekly_weekday_full_year_oracle():
    body = {
        "name": "w", "timezone": "America/New_York", "frequency": "weekly",
        "weekdays": [1, 3, 5], "at": "13:45",
        "start_date": "2024-01-01", "end_date": "2024-12-31",
        "executor": {"type": "log"},
    }
    spec = parse_spec(body)
    ref = reference_occurrences(spec, 2024)
    win = plan_window(spec, date(2024, 1, 1), date(2024, 12, 31))
    prod = [(f.due_utc, f.date_local, f.fold, f.kind.value) for f in win.fires]
    oracle = [(f.due_utc, f.date_local, f.fold, f.kind) for f in ref]
    assert prod == oracle
    # Weekday counts in leap year 2024: Mon=53, Wed=52, Fri=52 => 157.
    print(f"\n[oracle weekly] count={len(prod)}")
    assert len(prod) == 157


def test_monthly_nth_weekday_oracle():
    body = {
        "name": "n", "timezone": "America/New_York", "frequency": "monthly",
        "nth_weekdays": [{"nth": -1, "weekday": 7}, {"nth": 1, "weekday": 1}],
        "at": "04:00",  # safe from DST edges
        "start_date": "2024-01-01", "end_date": "2024-12-31",
        "executor": {"type": "log"},
    }
    spec = parse_spec(body)
    ref = reference_occurrences(spec, 2024)
    win = plan_window(spec, date(2024, 1, 1), date(2024, 12, 31))
    prod = [(f.due_utc, f.date_local, f.fold, f.kind.value) for f in win.fires]
    oracle = [(f.due_utc, f.date_local, f.fold, f.kind) for f in ref]
    assert prod == oracle
    assert len(prod) == 24  # two rules x 12 months
